/* ===== EDIT ME: business settings ===== */
const CFG={phone:'9059151235',wa:'https://wa.me/919059151235',ig:'https://www.instagram.com/food_by_devaki/',fb:'',yt:'',email:'',address:'',
adminPass:'devaki-admin', /* DEMO ONLY: client-side check. Replace with real server auth before launch. */
shipping:60,freeAbove:999,coupons:{WELCOME10:10}, /* code: % off */
announce:['Freshly Prepared Traditional Foods','Made with Love, Inspired by Tradition','Order Directly from Devaki Foods']};
/* Payment gateway hook: add real credentials/SDK here. Only COD is enabled until then. */
const PAY={cod:{label:'Cash on Delivery',on:true},upi:{label:'UPI',on:false},card:{label:'Credit/Debit Card',on:false},nb:{label:'Net Banking',on:false},
gateway:{provider:null,keyId:'ADD_KEY_ID_HERE',createOrderUrl:'ADD_SERVER_ENDPOINT_HERE'}};
async function startPayment(order){ /* replace with gateway order creation + checkout for non-COD methods */
 if(order.payment==='cod')return{status:'pending'};throw new Error('Payment gateway not configured');}
/* ===== EDIT ME: product data. Prices are DEMO values. ===== */
const DEF=[
{id:'minapa-laddu',name:'Minapa Laddu',cat:'Sweets',hue:38,desc:'Traditional Indian sweet made with urad dal (minapa).',long:'A traditional sweet made with urad dal (minapa). [Owner: add your own product description.]',sizes:[{l:'250g',p:180,mrp:0},{l:'500g',p:340,mrp:0},{l:'1kg',p:650,mrp:0}],featured:true,stock:true,rating:4.5,n:1,ing:'[Owner: add ingredients]',storage:'[Owner: add storage instructions]',shelf:'[Owner: add shelf life]'},
{id:'mango-pickle',name:'Mango Pickle',cat:'Pickles',hue:12,desc:'Traditional spicy Andhra-style mango pickle.',long:'A traditional spicy Andhra-style mango pickle. [Owner: add your own product description.]',sizes:[{l:'250g',p:160,mrp:0},{l:'500g',p:300,mrp:0},{l:'1kg',p:570,mrp:0}],featured:true,stock:true,rating:4.6,n:2,ing:'[Owner: add ingredients]',storage:'[Owner: add storage instructions]',shelf:'[Owner: add shelf life]'},
{id:'lemon-pickle',name:'Lemon Pickle',cat:'Pickles',hue:52,desc:'Traditional Indian lemon pickle.',long:'A traditional Indian lemon pickle. [Owner: add your own product description.]',sizes:[{l:'250g',p:150,mrp:0},{l:'500g',p:280,mrp:0},{l:'1kg',p:530,mrp:0}],featured:true,stock:true,rating:4.4,n:3,ing:'[Owner: add ingredients]',storage:'[Owner: add storage instructions]',shelf:'[Owner: add shelf life]'},
{id:'sana-atukula-chudava',name:'Sana Atukula Chudava',cat:'Snacks',hue:28,desc:'Traditional Indian snack made with atukulu (poha).',long:'A traditional snack made with atukulu (poha). [Owner: add your own product description.]',sizes:[{l:'250g',p:140,mrp:0},{l:'500g',p:260,mrp:0},{l:'1kg',p:490,mrp:0}],featured:true,stock:true,rating:4.3,n:4,ing:'[Owner: add ingredients]',storage:'[Owner: add storage instructions]',shelf:'[Owner: add shelf life]'}];
const CATS=['Sweets','Pickles','Snacks'],STAT=['Pending','Confirmed','Preparing','Shipped','Delivered','Cancelled'];
const REV=[['Sample reviewer A','Demo review: replace with a real customer review.'],['Sample reviewer B','Demo review: replace with a real customer review.'],['Sample reviewer C','Demo review: replace with a real customer review.']];
/* ===== helpers ===== */
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inr=n=>'₹'+Number(n).toLocaleString('en-IN');
const ld=(k,d)=>{try{const v=localStorage.getItem('df_'+k);return v?JSON.parse(v):d}catch(e){return d}};
const sv=(k,v)=>{try{localStorage.setItem('df_'+k,JSON.stringify(v))}catch(e){toast('Storage is full or blocked')}};
let P=ld('products',DEF),CART=ld('cart',[]),WISH=ld('wish',[]),ORD=ld('orders',[]),ADM=false,S={q:'',cat:'',sort:'popular',max:2000,step:1,cust:{},pay:'cod',coupon:'',off:0,g:0,qv:null,edit:null};
const svg=(h,i=0,t='Replace with photo')=>{const a=(h+i*40)%360;return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="hsl(${a},55%,82%)"/><stop offset="1" stop-color="hsl(${a},50%,62%)"/></linearGradient></defs><rect width="400" height="400" fill="url(#g)"/><circle cx="200" cy="200" r="130" fill="#fffdf7" opacity=".9"/><circle cx="200" cy="200" r="100" fill="hsl(${a},60%,55%)" opacity=".85"/><circle cx="170" cy="175" r="26" fill="hsl(${a},65%,70%)"/><circle cx="225" cy="215" r="34" fill="hsl(${a},55%,40%)" opacity=".7"/><text x="200" y="372" text-anchor="middle" font-family="Georgia,serif" font-size="18" fill="#3a2a1e" opacity=".7">${t}</text></svg>`)};
const img=(p,i=0)=>p.image&&i===0?p.image:svg(p.hue,i,p.image?'':'Replace with photo');
const stars=r=>'★'.repeat(Math.round(r))+'☆'.repeat(5-Math.round(r));
const I={s:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',u:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 15-5 16 0"/></svg>',h:'<svg viewBox="0 0 24 24"><path d="M12 20s-8-5-8-11a4.5 4.5 0 0 1 8-2.5A4.5 4.5 0 0 1 20 9c0 6-8 11-8 11z"/></svg>',c:'<svg viewBox="0 0 24 24"><path d="M5 7h14l-1.5 12h-11z"/><path d="M9 7a3 3 0 0 1 6 0"/></svg>',m:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>'};
const cnt=()=>CART.reduce((a,b)=>a+b.q,0),find=id=>P.find(p=>p.id===id);
function toast(m){const t=document.createElement('div');t.className='toast';t.setAttribute('role','status');t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function addCart(id,sz,q){const p=find(id);if(!p||!p.stock)return toast('This product is out of stock');const l=CART.find(c=>c.id===id&&c.sz===sz);l?l.q+=q:CART.push({id,sz,q});sv('cart',CART);hdr();toast(p.name+' added to cart')}
const sizeOf=(p,l)=>p.sizes.find(s=>s.l===l)||p.sizes[0];
function totals(){const sub=CART.reduce((a,c)=>{const p=find(c.id);return p?a+sizeOf(p,c.sz).p*c.q:a},0);const off=Math.round(sub*S.off/100);const ship=!sub?0:(sub-off>=CFG.freeAbove?0:CFG.shipping);return{sub,off,ship,tot:sub-off+ship}}
/* ===== components ===== */
function card(p){const s=p.sizes[0];return `<article class="card"><a class="im" href="#/p/${p.id}"><img src="${img(p)}" alt="${esc(p.name)} (placeholder image)" loading="lazy">${p.featured?'<span class="tag">Featured</span>':''}${!p.stock?'<span class="tag" style="background:#ddd">Out of stock</span>':''}</a><button class="heart" data-a="wish" data-id="${p.id}" aria-label="Toggle wishlist">${WISH.includes(p.id)?'♥':'♡'}</button>
<div class="bd"><h3><a href="#/p/${p.id}">${esc(p.name)}</a></h3><p>${esc(p.desc)}</p><div class="st" aria-label="Rating ${p.rating}">${stars(p.rating)} <small>(${p.rating})</small></div><div class="pr" data-pr>${inr(s.p)}</div>
<div class="two"><select data-sz aria-label="Package size">${p.sizes.map(z=>`<option value="${esc(z.l)}" data-p="${z.p}">${esc(z.l)}</option>`).join('')}</select><input data-qt type="number" min="1" max="20" value="1" aria-label="Quantity"></div>
<div class="two2"><button class="btn sm o" data-a="add" data-id="${p.id}" ${p.stock?'':'disabled'}>Add to Cart</button><button class="btn sm" data-a="buy" data-id="${p.id}" ${p.stock?'':'disabled'}>Buy Now</button></div><button class="btn sm o" style="border-color:var(--line);color:var(--mute)" data-a="qv" data-id="${p.id}">Quick view</button></div></article>`}
function hdr(){const h=`<div class="ann" id="ann">${esc(CFG.announce[0])}</div><header><div class="w nav"><button class="ib burger" data-a="menu" aria-label="Menu">${I.m}</button><a class="logo" href="#/">DEVAKI<small>FOODS</small></a>
<nav class="menu" id="menu" aria-label="Main">${[['','Home'],['shop','Shop'],['shop','Categories','cats'],['about','About Us'],['contact','Contact']].map(([r,t,x])=>`<a href="#/${r}${x?'?cats':''}" ${x?'data-a="cats"':''}>${t}</a>`).join('')}</nav>
<div class="ico"><button class="ib" data-a="srch" aria-label="Search">${I.s}</button><a class="ib" href="#/admin" aria-label="Account / owner login">${I.u}</a><a class="ib" href="#/wishlist" aria-label="Wishlist">${I.h}${WISH.length?`<span class="bdg">${WISH.length}</span>`:''}</a><a class="ib" href="#/cart" aria-label="Cart, ${cnt()} items">${I.c}<span class="bdg">${cnt()}</span></a></div></div>
<div class="w sbar" id="sbar"><form data-f="search"><input name="q" type="search" placeholder="Search products…" aria-label="Search products"></form></div></header>`;
$('#hd').innerHTML=h;let i=0;clearInterval(window._an);window._an=setInterval(()=>{i=(i+1)%CFG.announce.length;const a=$('#ann');if(a)a.textContent=CFG.announce[i]},4000)}
const soc=(u,t)=>u?`<a href="${u}" target="_blank" rel="noopener">${t}</a>`:`<a style="opacity:.5;pointer-events:none">${t} (add link in CFG)</a>`;
function ftr(){return `<footer><div class="w"><div class="fg"><div><div class="logo" style="color:#f3cf6b">DEVAKI<small>FOODS</small></div><p style="opacity:.8">Taste of Tradition, Made with Love.</p></div>
<div><h4>Shop</h4><a href="#/shop">All Products</a>${CATS.map(c=>`<a href="#/shop?c=${c}">${c}</a>`).join('')}</div>
<div><h4>Information</h4><a href="#/about">About Us</a><a href="#/contact">Contact Us</a>${[['shipping','Shipping & Delivery'],['returns','Returns & Refunds'],['privacy','Privacy Policy'],['terms','Terms & Conditions'],['faq','FAQ']].map(([k,t])=>`<a href="#/info/${k}">${t}</a>`).join('')}</div>
<div><h4>Contact</h4><a href="tel:${CFG.phone}">${CFG.phone}</a><a href="${CFG.wa}" target="_blank" rel="noopener">WhatsApp</a></div>
<div><h4>Social</h4>${soc(CFG.ig,'Instagram')}${soc(CFG.fb,'Facebook')}${soc(CFG.yt,'YouTube')}</div></div><div class="copy">© 2026 Devaki Foods. All rights reserved.</div></div></footer>`}
/* ===== pages ===== */
const pages={
home(){const f=P.filter(p=>p.featured);return `<section class="hero"><div class="w"><div><h1>Authentic Taste of Home</h1><p>Traditional sweets, pickles and snacks made with the flavors we grew up loving.</p><div class="row"><a class="btn g" href="#/shop">Shop Now</a><a class="btn o" style="color:#3a2a1e;border-color:#3a2a1e" href="#featured" data-a="feat">Explore Our Products</a></div></div><img src="${svg(38,1,'Hero photo placeholder')}" alt="Placeholder for hero food photograph"></div></section>
<section class="sec"><div class="w g4">${[['Traditional Taste','Recipes inspired by timeless Indian traditions.'],['Made with Care','Prepared with attention to taste and quality.'],['Homestyle Flavours','Bringing the comfort of homemade food to your doorstep.'],['Freshly Packed','Products packed carefully for a great experience.']].map(([a,b])=>`<div class="box val"><h3>${a}</h3><p>${b}</p></div>`).join('')}</div></section>
<section class="sec" style="padding-top:0"><div class="w"><h2>Shop by Category</h2><div class="g3">${CATS.map((c,i)=>`<a class="cat" href="#/shop?c=${c}"><img src="${svg([38,12,28][i],i+1,'')}" alt=""><span>${c}</span></a>`).join('')}</div></div></section>
<section class="sec" id="featured"><div class="w"><h2>Featured Products</h2><div class="g4">${f.map(card).join('')||'<p>No featured products yet.</p>'}</div></div></section>
<section class="sec"><div class="w why"><div><h2>From Our Kitchen to Your Home</h2><p>Devaki Foods brings traditional Indian flavours to the modern home. Our aim is simple: make the food we love easy to enjoy and share.</p><a class="btn g" href="#/about">Read our story</a></div><img src="${svg(52,2,'Kitchen photo placeholder')}" alt="Placeholder for kitchen photograph"></div></section>
<section class="sec" style="padding-top:0"><div class="w"><h2>What customers say</h2><p class="demo">Sample/demo reviews. Replace with real customer reviews in REV.</p><div class="g3">${REV.map(r=>`<div class="box"><div class="st">★★★★★</div><p class="q">“${r[1]}”</p><b>${r[0]}</b> <span class="demo">(demo)</span></div>`).join('')}</div></div></section>
<section class="sec" style="padding-top:0"><div class="w"><h2>Follow along</h2><div class="soc">${[38,12,52,28,80,140].map((h,i)=>`<img src="${svg(h,i,'Social photo')}" alt="Placeholder social photo">`).join('')}</div><p>${CFG.ig?`<a class="btn o sm" href="${CFG.ig}" target="_blank" rel="noopener">Instagram: @food_by_devaki</a>`:'Add your Instagram link in CFG.ig'}</p></div></section>
<section class="sec" style="padding-top:0"><div class="w"><div class="nl"><h2>Stay Connected with Devaki Foods</h2><form data-f="news"><input type="email" name="e" required placeholder="Email address" aria-label="Email address"><button class="btn">Subscribe</button></form></div></div></section>`},
shop(){const l=list();return `<div class="w sec"><h1 style="font-size:2.6rem">${S.wish?'Wishlist':S.cat||'All Products'}</h1><div class="shop"><aside class="filt"><div class="box"><div><label for="fq">Search</label><input id="fq" data-s="q" value="${esc(S.q)}" placeholder="Search…"></div><div><label for="fc">Category</label><select id="fc" data-s="cat"><option value="">All Products</option>${CATS.map(c=>`<option ${S.cat===c?'selected':''}>${c}</option>`).join('')}</select></div><div><label for="fs">Sort by</label><select id="fs" data-s="sort">${[['popular','Popularity'],['new','Newest'],['low','Price: low to high'],['high','Price: high to low']].map(([v,t])=>`<option value="${v}" ${S.sort===v?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="fm">Max price (from ${inr(0)}): <b id="mv">${inr(S.max)}</b></label><input id="fm" type="range" min="100" max="2000" step="50" value="${S.max}" data-s="max"></div></div></aside><div><p id="rc">${l.length} products</p><div class="g4" id="pl">${l.map(card).join('')||'<p>No products match. Try clearing filters.</p>'}</div></div></div></div>`},
product(id){const p=find(id);if(!p)return nf();const s=p.sizes[0],rel=P.filter(x=>x.id!==id&&x.cat===p.cat).concat(P.filter(x=>x.id!==id&&x.cat!==p.cat)).slice(0,3);return `<div class="w sec"><p><a href="#/shop">← Shop</a> / ${esc(p.cat)}</p><div class="pd" data-pid="${p.id}"><div><img class="main" id="mi" src="${img(p)}" alt="${esc(p.name)} (placeholder image)"><div class="th">${[0,1,2].map(i=>`<img src="${img(p,i)}" class="${i?'':'on'}" data-a="th" alt="View ${i+1}" tabindex="0">`).join('')}</div></div>
<div><h1 style="font-size:2.6rem">${esc(p.name)}</h1><div class="st">${stars(p.rating)} <small>(${p.rating})</small></div><p>${esc(p.long)}</p><div class="pr" style="font-size:1.8rem" id="dp">${inr(s.p)}${s.mrp>s.p?`<span class="mrp">${inr(s.mrp)}</span>`:''}</div><label>Package size</label><div class="chips" id="sz">${p.sizes.map((z,i)=>`<button class="chip ${i?'':'on'}" data-a="size" data-p="${z.p}" data-m="${z.mrp||0}" data-l="${esc(z.l)}">${esc(z.l)}</button>`).join('')}</div><br><label>Quantity</label><div class="qty"><button data-a="dq" aria-label="Decrease">−</button><b id="dqv">1</b><button data-a="iq" aria-label="Increase">+</button></div>
<div class="row"><button class="btn" data-a="dadd" ${p.stock?'':'disabled'}>Add to Cart</button><button class="btn g" data-a="dbuy" ${p.stock?'':'disabled'}>Buy Now</button></div>${p.stock?'':'<p><b>Currently out of stock</b></p>'}
<p class="note" style="margin-top:18px">Prices shown are demo values until the owner sets real prices.</p><h3 style="margin-top:24px">Ingredients</h3><p>${esc(p.ing)}</p><h3>Storage instructions</h3><p>${esc(p.storage)}</p><h3>Shelf life</h3><p>${esc(p.shelf)}</p><h3>Delivery information</h3><p>Shipping ${inr(CFG.shipping)}; free above ${inr(CFG.freeAbove)}. Delivery timelines: [Owner: add details].</p></div></div>
<h2 style="margin-top:48px">Customer reviews</h2><div class="g3">${REV.map(r=>`<div class="box"><div class="st">★★★★☆</div><p>${r[1]}</p><b>${r[0]}</b> <span class="demo">(demo)</span></div>`).join('')}</div><h2 style="margin-top:48px">Related products</h2><div class="g4">${rel.map(card).join('')}</div></div>
<div class="sticky"><b id="sp">${inr(s.p)}</b><button class="btn" data-a="dadd" ${p.stock?'':'disabled'}>Add to Cart</button></div>`},
cart(){const t=totals();return `<div class="w sec"><h1 style="font-size:2.6rem">Your Cart</h1>${!CART.length?`<p>Your cart is empty.</p><a class="btn" href="#/shop">Continue Shopping</a>`:`<div class="cl"><div>${CART.map((c,i)=>{const p=find(c.id);if(!p)return'';const s=sizeOf(p,c.sz);return `<div class="ci"><img src="${img(p)}" alt=""><div><b>${esc(p.name)}</b><br><select data-cs="${i}" aria-label="Size" style="width:auto;padding:4px 8px">${p.sizes.map(z=>`<option ${z.l===c.sz?'selected':''}>${esc(z.l)}</option>`).join('')}</select><br><div class="qty" style="margin-top:6px"><button data-a="cq" data-i="${i}" data-d="-1" aria-label="Decrease">−</button><b>${c.q}</b><button data-a="cq" data-i="${i}" data-d="1" aria-label="Increase">+</button></div> <button class="chip" data-a="rm" data-i="${i}">Remove</button></div><b>${inr(s.p*c.q)}</b></div>`}).join('')}<p><a href="#/shop">← Continue Shopping</a></p></div>
<div class="box sum">${sumHtml(t)}<div style="display:flex;gap:8px;margin:12px 0"><input id="cp" placeholder="Coupon code" value="${esc(S.coupon)}" aria-label="Coupon code"><button class="btn sm" data-a="coupon">Apply</button></div><a class="btn" style="display:block" href="#/checkout">Proceed to Checkout</a></div></div>`}</div>`},
checkout(){if(!CART.length)return `<div class="w sec"><p>Your cart is empty.</p><a class="btn" href="#/shop">Continue Shopping</a></div>`;const t=totals(),c=S.cust,F=(n,l,ty='text',x='')=>`<div class="${x}"><label for="c${n}">${l}</label><input id="c${n}" name="${n}" type="${ty}" value="${esc(c[n]||'')}" autocomplete="on"><div class="err" id="e${n}"></div></div>`;
return `<div class="w sec"><h1 style="font-size:2.6rem">Checkout</h1><div class="steps"><span class="${S.step===1?'on':''}">1. Your details</span><span class="${S.step===2?'on':''}">2. Payment</span></div><div class="cl"><div class="box">${S.step===1?`<form data-f="cust" class="fgrid" novalidate>${F('name','Full Name','text','f')}${F('mobile','Mobile Number','tel')}${F('email','Email','email')}${F('address','Address','text','f')}${F('landmark','Landmark')}${F('city','City')}${F('state','State')}${F('pin','PIN Code','text')}<div class="f"><button class="btn">Continue to payment</button></div></form>`:`<h3>Payment method</h3>${Object.entries(PAY).filter(([k])=>k!=='gateway').map(([k,m])=>`<label class="pay ${m.on?'':'dis'}"><input type="radio" name="pm" value="${k}" ${S.pay===k?'checked':''} ${m.on?'':'disabled'} data-a="pm"> ${m.label}${m.on?'':'<em>Coming Soon</em>'}</label>`).join('')}<p class="demo">Payment gateway not connected. Orders are placed as Cash on Delivery.</p><div class="row"><button class="btn o" data-a="back">Back</button><button class="btn" data-a="place">Place Order</button></div>`}</div><div class="box sum"><h3>Order summary</h3>${CART.map(c=>{const p=find(c.id);return p?`<div><span>${esc(p.name)} (${esc(c.sz)}) × ${c.q}</span><span>${inr(sizeOf(p,c.sz).p*c.q)}</span></div>`:''}).join('')}${sumHtml(t)}</div></div></div>`},
confirm(id){const o=ORD.find(x=>x.id===id);if(!o)return nf();return `<div class="w sec" style="max-width:720px"><h1>Thank You for Your Order!</h1><div class="box sum"><div><span>Order ID</span><b>${o.id}</b></div><div><span>Customer</span><span>${esc(o.cust.name)}</span></div><div><span>Delivery address</span><span style="text-align:right">${esc(o.cust.address)}, ${esc(o.cust.landmark)} ${esc(o.cust.city)}, ${esc(o.cust.state)} ${esc(o.cust.pin)}</span></div><div><span>Payment method</span><span>${PAY[o.payment].label}</span></div><div><span>Order status</span><b>${o.status}</b></div>${o.items.map(i=>`<div><span>${esc(i.name)} (${esc(i.sz)}) × ${i.q}</span><span>${inr(i.p*i.q)}</span></div>`).join('')}<div class="t"><span>Total</span><span>${inr(o.total)}</span></div></div><h3 style="margin-top:28px">Need help with your order?</h3><p>Call <a href="tel:${CFG.phone}"><b>${CFG.phone}</b></a></p><a class="btn" href="#/contact">Contact Devaki Foods</a></div>`},
about(){const ph=t=>`<div class="box"><b>${t}</b><p class="demo">[Placeholder: owner to add]</p></div>`;return `<div class="w sec" style="max-width:860px"><h1>Our Story</h1><p style="font-size:1.15rem">Devaki Foods is focused on traditional Indian tastes and on bringing homemade-style food to customers. We make sweets, pickles and snacks inspired by the flavours many of us grew up with.</p><img src="${svg(38,1,'Real photo placeholder')}" alt="Placeholder photograph" style="border-radius:20px;margin:24px 0;width:100%;max-height:380px;object-fit:cover"><div class="g3">${['Founder story','Brand history','Location','Mission','Food preparation story','Real photographs'].map(ph).join('')}</div></div>`},
contact(){return `<div class="w sec"><h1>Contact</h1><div class="cl"><div class="box"><h3>Devaki Foods</h3><p><b>Phone:</b> <a href="tel:${CFG.phone}">${CFG.phone}</a></p><p><b>Email:</b> ${CFG.email?`<a href="mailto:${CFG.email}">${esc(CFG.email)}</a>`:'<span class="demo">[Placeholder: add email in CFG.email]</span>'}</p><p><b>Address:</b> ${CFG.address?esc(CFG.address):'<span class="demo">[Placeholder: add address in CFG.address]</span>'}</p><p><b>Instagram:</b> <a href="${CFG.ig}" target="_blank" rel="noopener">@food_by_devaki</a></p><p><b>Facebook:</b> ${CFG.fb?`<a href="${CFG.fb}">Facebook</a>`:'<span class="demo">[Placeholder]</span>'}</p><div class="row"><a class="btn" href="tel:${CFG.phone}">Call Now</a><a class="btn g" href="${CFG.wa}" target="_blank" rel="noopener">WhatsApp Us</a></div></div><form class="box" data-f="msg"><div style="display:grid;gap:12px"><div><label for="mn">Name</label><input id="mn" name="n" required></div><div><label for="mp">Phone</label><input id="mp" name="p" type="tel" required></div><div><label for="me">Email</label><input id="me" name="e" type="email"></div><div><label for="mm">Message</label><textarea id="mm" name="m" rows="4" required></textarea></div><button class="btn">Send message</button><p class="demo">Messages are saved for the owner in the admin panel until an email service is connected.</p></div></form></div></div>`},
info(k){const T={shipping:'Shipping & Delivery',returns:'Returns & Refunds',privacy:'Privacy Policy',terms:'Terms & Conditions',faq:'FAQ'};if(!T[k])return nf();return `<div class="w sec" style="max-width:760px"><h1>${T[k]}</h1><p class="note">[Placeholder: the owner needs to add the official ${T[k]} text here.]</p>${k==='shipping'?`<p>Current settings: shipping ${inr(CFG.shipping)}, free above ${inr(CFG.freeAbove)}.</p>`:''}<p>Questions? Call <a href="tel:${CFG.phone}">${CFG.phone}</a>.</p></div>`},
admin(){if(!ADM)return `<div class="w sec" style="max-width:420px"><h1 style="font-size:2.2rem">Owner login</h1><form class="box" data-f="login" style="display:grid;gap:12px"><div><label for="ap">Password</label><input id="ap" type="password" name="p" autocomplete="current-password"></div><div class="err" id="ae"></div><button class="btn">Log in</button><p class="demo">Demo protection only, in this browser. Real security needs a server (see CFG.adminPass).</p></form></div>`;
const e=S.edit;return `<div class="w sec"><div class="row" style="justify-content:space-between;margin:0 0 16px"><h1 style="font-size:2.2rem;margin:0">Admin</h1><button class="btn o sm" data-a="logout">Log out</button></div><h2>Products</h2><div class="ov"><table class="tbl"><tr><th>Name</th><th>Category</th><th>Prices</th><th>Flags</th><th></th></tr>${P.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.cat}</td><td>${p.sizes.map(z=>z.l+' '+inr(z.p)).join(', ')}</td><td>${p.featured?'Featured ':''}${p.stock?'':'Out of stock'}</td><td><button class="btn sm o" data-a="ed" data-id="${p.id}">Edit</button> <button class="btn sm o" data-a="del" data-id="${p.id}">Delete</button></td></tr>`).join('')}</table></div><p><button class="btn sm" data-a="new">Add product</button></p>
${e?`<form class="box" data-f="prod" style="display:grid;gap:12px;margin-top:16px"><h3>${e.id?'Edit':'Add'} product</h3><div><label>Name</label><input name="name" required value="${esc(e.name)}"></div><div><label>Category</label><select name="cat">${CATS.map(c=>`<option ${e.cat===c?'selected':''}>${c}</option>`).join('')}</select></div><div><label>Short description</label><input name="desc" value="${esc(e.desc)}"></div><div><label>Full description</label><textarea name="long" rows="3">${esc(e.long)}</textarea></div><div><label>Package sizes and prices (one per line: size | price | MRP optional)</label><textarea name="sizes" rows="4">${e.sizes.map(z=>`${z.l} | ${z.p}${z.mrp?' | '+z.mrp:''}`).join('\n')}</textarea></div><div><label>Ingredients</label><input name="ing" value="${esc(e.ing)}"></div><div><label>Storage</label><input name="storage" value="${esc(e.storage)}"></div><div><label>Shelf life</label><input name="shelf" value="${esc(e.shelf)}"></div><div><label>Image upload (small files, saved in browser)</label><input type="file" accept="image/*" name="file"></div><label><input type="checkbox" name="featured" style="width:auto" ${e.featured?'checked':''}> Featured</label><label><input type="checkbox" name="stock" style="width:auto" ${e.stock?'checked':''}> In stock</label><div class="row" style="margin:0"><button class="btn">Save product</button><button type="button" class="btn o" data-a="cancel">Cancel</button></div></form>`:''}
<h2 style="margin-top:40px">Orders</h2>${!ORD.length?'<p>No orders yet.</p>':`<div class="ov"><table class="tbl"><tr><th>ID</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr>${ORD.map((o,i)=>`<tr><td>${o.id}<br><span class="demo">${new Date(o.at).toLocaleString('en-IN')}</span></td><td>${esc(o.cust.name)}<br>${esc(o.cust.mobile)}<br>${esc(o.cust.address)}, ${esc(o.cust.city)} ${esc(o.cust.pin)}</td><td>${o.items.map(x=>`${esc(x.name)} ${esc(x.sz)}×${x.q}`).join('<br>')}</td><td>${inr(o.total)}<br>${PAY[o.payment].label}</td><td><select data-os="${i}" aria-label="Order status">${STAT.map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</table></div>`}
<h2 style="margin-top:40px">Messages</h2>${ld('msgs',[]).map(m=>`<div class="box" style="margin-bottom:8px"><b>${esc(m.n)}</b> ${esc(m.p)} ${esc(m.e)}<br>${esc(m.m)}</div>`).join('')||'<p>None yet.</p>'}</div>`}};
const nf=()=>`<div class="w sec"><h1>Page not found</h1><a class="btn" href="#/">Back to home</a></div>`;
const sumHtml=t=>`<div><span>Subtotal</span><span>${inr(t.sub)}</span></div><div><span>Discount${S.off?` (${S.off}%)`:''}</span><span>−${inr(t.off)}</span></div><div><span>Shipping</span><span>${t.ship?inr(t.ship):'Free'}</span></div><div class="t"><span>Total</span><span>${inr(t.tot)}</span></div>`;
function list(){let l=P.filter(p=>(!S.cat||p.cat===S.cat)&&(!S.wish||WISH.includes(p.id))&&p.sizes[0].p<=S.max&&(p.name+p.desc+p.cat).toLowerCase().includes(S.q.toLowerCase()));const k=S.sort;return l.sort((a,b)=>k==='low'?a.sizes[0].p-b.sizes[0].p:k==='high'?b.sizes[0].p-a.sizes[0].p:k==='new'?(b.n||0)-(a.n||0):b.rating-a.rating)}
/* ===== router ===== */
function route(){const h=location.hash.slice(2)||'',[path,qs]=h.split('?'),[r,a]=path.split('/');const q=new URLSearchParams(qs||'');S.wish=r==='wishlist';if(r==='shop'||r==='wishlist'){if(q.has('c'))S.cat=q.get('c');else if(r==='shop'&&!q.has('cats'))S.cat=S.cat}
let v;switch(r){case'':v=pages.home();break;case'shop':case'wishlist':v=pages.shop();break;case'p':v=pages.product(a);break;case'cart':v=pages.cart();break;case'checkout':v=pages.checkout();break;case'confirm':v=pages.confirm(a);break;case'about':v=pages.about();break;case'contact':v=pages.contact();break;case'info':v=pages.info(a);break;case'admin':v=pages.admin();break;default:v=nf()}
$('#main').innerHTML=v;const T={'':'Devaki Foods | Traditional Indian Sweets, Pickles & Snacks',shop:'Shop | Devaki Foods',cart:'Cart | Devaki Foods',checkout:'Checkout | Devaki Foods',about:'Our Story | Devaki Foods',contact:'Contact | Devaki Foods'};document.title=(r==='p'&&find(a)?find(a).name+' | Devaki Foods':T[r]||'Devaki Foods');if(!window._keep)scrollTo(0,0);window._keep=0;hdr()}
function reList(){const l=list();$('#pl').innerHTML=l.map(card).join('')||'<p>No products match. Try clearing filters.</p>';$('#rc').textContent=l.length+' products';const m=$('#mv');if(m)m.textContent=inr(S.max)}
function place(){const t=totals(),o={id:'DF'+Date.now().toString(36).toUpperCase(),at:Date.now(),cust:S.cust,payment:S.pay,status:'Pending',subtotal:t.sub,discount:t.off,shipping:t.ship,total:t.tot,items:CART.map(c=>{const p=find(c.id);return{id:c.id,name:p.name,sz:c.sz,q:c.q,p:sizeOf(p,c.sz).p}})};
startPayment(o).then(()=>{ORD.unshift(o);sv('orders',ORD);CART=[];sv('cart',CART);S.step=1;S.off=0;S.coupon='';location.hash='#/confirm/'+o.id}).catch(e=>toast(e.message))}
/* ===== events ===== */
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a,id=b.dataset.id,cd=b.closest('.card'),pid=()=>$('.pd')?.dataset.pid;
if(a==='menu')$('#menu').classList.toggle('open');else if(a==='srch'){$('#sbar').classList.toggle('open');$('#sbar input').focus()}
else if(a==='cats'){e.preventDefault();S.cat='';location.hash='#/shop?cats'}else if(a==='feat'){e.preventDefault();$('#featured').scrollIntoView()}
else if(a==='wish'){WISH=WISH.includes(id)?WISH.filter(x=>x!==id):[...WISH,id];sv('wish',WISH);b.textContent=WISH.includes(id)?'♥':'♡';hdr()}
else if(a==='add'||a==='buy'){addCartFrom(cd,id,a==='buy')}
else if(a==='qv'){const p=find(id);S.qv=p;const m=document.createElement('div');m.className='mod';m.innerHTML=`<div class="box" role="dialog" aria-label="Quick view"><button class="btn sm o" data-a="close" style="float:right">Close</button><div class="g3"><img src="${img(p)}" alt="" style="border-radius:14px"><div><h2>${esc(p.name)}</h2><p>${esc(p.long)}</p><p class="pr">From ${inr(p.sizes[0].p)}</p><a class="btn" href="#/p/${p.id}" data-a="close">View full details</a></div></div></div>`;document.body.appendChild(m)}
else if(a==='close'){document.querySelector('.mod')?.remove()}
else if(a==='th'){$$('.th img').forEach(i=>i.classList.remove('on'));b.classList.add('on');$('#mi').src=b.src}
else if(a==='size'){$$('#sz .chip').forEach(c=>c.classList.remove('on'));b.classList.add('on');const p=+b.dataset.p,m=+b.dataset.m;$('#dp').innerHTML=inr(p)+(m>p?`<span class="mrp">${inr(m)}</span>`:'');$('#sp').textContent=inr(p)}
else if(a==='dq'||a==='iq'){const v=$('#dqv');v.textContent=Math.max(1,Math.min(20,+v.textContent+(a==='iq'?1:-1)))}
else if(a==='dadd'||a==='dbuy'){addCart(pid(),$('#sz .on').dataset.l,+$('#dqv').textContent);if(a==='dbuy')location.hash='#/checkout'}
else if(a==='cq'){const c=CART[+b.dataset.i];c.q=Math.max(1,Math.min(20,c.q+ +b.dataset.d));sv('cart',CART);window._keep=1;route()}
else if(a==='rm'){CART.splice(+b.dataset.i,1);sv('cart',CART);window._keep=1;route()}
else if(a==='coupon'){const c=$('#cp').value.trim().toUpperCase();if(CFG.coupons[c]){S.off=CFG.coupons[c];S.coupon=c;toast('Coupon applied')}else{S.off=0;S.coupon='';toast('Invalid coupon code')}window._keep=1;route()}
else if(a==='back'){S.step=1;route()}else if(a==='place')place();else if(a==='pm')S.pay=b.value;
else if(a==='logout'){ADM=false;route()}else if(a==='new'){S.edit={name:'',cat:'Sweets',hue:30,desc:'',long:'',sizes:[{l:'250g',p:0,mrp:0}],featured:false,stock:true,rating:4,n:Date.now(),ing:'',storage:'',shelf:''};window._keep=1;route()}
else if(a==='ed'){S.edit={...find(id)};window._keep=1;route()}else if(a==='cancel'){S.edit=null;window._keep=1;route()}
else if(a==='del'){if(confirm('Delete this product?')){P=P.filter(p=>p.id!==id);sv('products',P);window._keep=1;route()}}});
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function addCartFrom(cd,id,buy){addCart(id,cd.querySelector('[data-sz]').value,Math.max(1,Math.min(20,+cd.querySelector('[data-qt]').value||1)));if(buy)location.hash='#/checkout'}
document.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-sz]')){t.closest('.card').querySelector('[data-pr]').textContent=inr(t.selectedOptions[0].dataset.p)}
else if(t.matches('[data-s]')){const k=t.dataset.s;S[k]=k==='max'?+t.value:t.value;reList()}
else if(t.matches('[data-cs]')){CART[+t.dataset.cs].sz=t.value;const d=CART.findIndex((c,i)=>i!==+t.dataset.cs&&c.id===CART[+t.dataset.cs].id&&c.sz===t.value);if(d>-1){CART[d].q+=CART[+t.dataset.cs].q;CART.splice(+t.dataset.cs,1)}sv('cart',CART);window._keep=1;route()}
else if(t.matches('[data-os]')){ORD[+t.dataset.os].status=t.value;sv('orders',ORD);toast('Status updated')}});
document.addEventListener('input',e=>{if(e.target.matches('[data-s="q"]')){S.q=e.target.value;reList()}else if(e.target.matches('[data-s="max"]')){S.max=+e.target.value;reList()}});
document.addEventListener('submit',e=>{const f=e.target.dataset.f;if(!f)return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target));
if(f==='search'){S.q=d.q;S.cat='';$('#sbar').classList.remove('open');location.hash='#/shop';route()}
else if(f==='news'){const n=ld('news',[]);n.push(d.e);sv('news',n);e.target.reset();toast('Subscribed. Thank you!')}
else if(f==='msg'){const m=ld('msgs',[]);m.unshift(d);sv('msgs',m);e.target.reset();toast('Message sent. We will get back to you.')}
else if(f==='login'){if(d.p===CFG.adminPass){ADM=true;route()}else $('#ae').textContent='Incorrect password.'}
else if(f==='cust'){const er={};if(!d.name.trim())er.name='Enter your full name';if(!/^[6-9]\d{9}$/.test(d.mobile.replace(/\s/g,'')))er.mobile='Enter a valid 10-digit mobile number';if(!/^\S+@\S+\.\S+$/.test(d.email))er.email='Enter a valid email';if(!d.address.trim())er.address='Enter your address';if(!d.city.trim())er.city='Enter your city';if(!d.state.trim())er.state='Enter your state';if(!/^\d{6}$/.test(d.pin))er.pin='Enter a 6-digit PIN code';
S.cust=d;$$('.err').forEach(x=>x.textContent='');Object.entries(er).forEach(([k,v])=>{$('#e'+k).textContent=v});if(!Object.keys(er).length){S.step=2;route()}}
else if(f==='prod'){const ed=S.edit,fin=()=>{const sizes=d.sizes.split('\n').map(l=>l.split('|').map(x=>x.trim())).filter(x=>x[0]&&+x[1]>0).map(x=>({l:x[0],p:+x[1],mrp:+x[2]||0}));if(!sizes.length)return toast('Add at least one size with a price');
const p={...ed,name:d.name,cat:d.cat,desc:d.desc,long:d.long,sizes,ing:d.ing,storage:d.storage,shelf:d.shelf,featured:!!d.featured,stock:!!d.stock};if(!p.id)p.id=d.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36);const i=P.findIndex(x=>x.id===p.id);i>-1?P[i]=p:P.push(p);sv('products',P);S.edit=null;window._keep=1;route();toast('Product saved')};
const fl=e.target.file.files[0];if(fl){if(fl.size>600000)return toast('Image too large. Use one under 600 KB.');const r=new FileReader();r.onload=()=>{ed.image=r.result;fin()};r.readAsDataURL(fl)}else fin()}});
window.addEventListener('hashchange',route);
$('#root').innerHTML='<div id="hd"></div><main id="main"></main>'+ftr();route();
